//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4262021
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOPSH
    {
        public int ID_Lop { get; set; }
        public string NameLop { get; set; }
    }
}
